### ISSUE TITLE
how did you decompile this

### ISSUE THREAD

**Issue by 12brendon34** [KadeDev/Horizon-Injector-Cracked-Source#3]
it would be nice to know how you did this i have tried decompiling confuser ex and most the time only some can be decompiled I just want to know how you did this so I can apply it to other applications thank you

**Comment by 12brendon34** [comment]
@KadeDev sorry for the @/email but i dont think you will see this if i dont

**Comment by 12brendon34** [comment]
if you see this can you please tell me i am going to stop commenting because you probly will not see this

**Comment by CallumCPP** [comment]
im assuming he used dnSpy to decompile it but i dont know how he decryupted it. its encrypted using confuserex if that helps

**Comment by A9039** [comment]
> im assuming he used dnSpy to decompile it but i dont know how he decryupted it. its encrypted using confuserex if that helps

prob, what's your discord?
